main: com.sekwah.advancedportals.AdvancedPortalsPlugin
name: AdvancedPortals
version: 0.1.0
author: sekwah41
description: An advanced portals plugin for bukkit.
commands:
    advancedportals:
        description: The main command for the advanced portals
        aliases: [portals, aportals, portal, ap]
        usage: /<command>
    destination:
        description: Can be used to access portal destinations.
        aliases: [desti]
        usage: /<command>
permissions:
   advancedportals.*:
     description: Gives access to all commands
     children:
       advancedportals.createportal: true
       advancedportals.portal: true
       advancedportals.build: true
       advancedportals.desti: true
       advancedportals.warp.*: true
   advancedportals.createportal:
     description: Allows you to create portals
     default: op
   advancedportals.portal:
     description: Allows use of portal commands
     default: op
   advancedportals.build:
     description: Allows you to build in the portal regions
     default: op
   advancedportals.desti:
     description: Gives access to all desti commands
     default: op
   advancedportals.warp.*:
     description: Access to all warps
     default: true
